History=History
failingFor=Failing for the past {0} {0,choice,0#builds|1#build|1<builds}
skippedFor=Skipped for the past {0} {0,choice,0#builds|1#build|1<builds}
took=Took {0}
since.before=since' '
since.after=' '
Error\ Details=Error Details
Skip\ Message=Skip Message
Stack\ Trace=Stack Trace
Standard\ Output=Standard Output
Standard\ Error=Standard Error
copyAsPrompt=Copy as prompt
copyAsPromptMessage=Copied the failure prompt to the clipboard.
